// react-redux/src/comp/TodoHeader.js
import React, {
    Component
} from 'react';
import Storage from '../helper/Storage';

class TodoHeader extends Component {
    keydownHandler(event) {
        console.log(event.keyCode);
        if (event.keyCode === 13) {
            Storage.addItem({
                message: this.state.input,
                completed: false
            });
            this.setState({
                input:''
            });
            this.props.updateItem();
        }
    }
    changeHandler(event) {
        // console.log(event);
        this.setState({
            input: event.target.value
        })
    }
    constructor(props) {
        super(props);

        this.state = {
            input: ''
        };
    }
    render() {
        const {changeHandler,keydownHandler} = this;
        return (
        <header className="header">
          <h1>todos</h1>
          <input onChange={changeHandler.bind(this)} onKeyDown={keydownHandler.bind(this)} value={this.state.input} autoFocus="autofocus" autoComplete="off" placeholder="请填写代办事项" className="new-todo"/>
        </header>
        );
    }
}

export default TodoHeader;

// vue-vuex/src/components/TodoHeader.vue
<template>
    <header class="header">
        <h1>{{title}}</h1>
        <input autofocus="autofocus" autocomplete="off" :placeholder="placeholder"
               @keyup.enter="todoInputHandler($event)" v-model="todoInput" class="new-todo">
    </header>
</template>

<script>
    export default {
        data: ()=>({
            title: "todos",
            placeholder: "请填写代办事项",
            todoInput: "",
        }),
        methods: {
            todoInputHandler(event) {
                console.log("event", event);
                let val = this.todoInput;
                if (!val || !val.trim()) return;
                //清空输入
                this.todoInput = "";
                //发送事件
                this.$emit('add-todo',val);
            },
        },
    }
</script>
